name: Release

permissions:
  contents: write

on:
  push:
    branches: 
      - 'experiment'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: 打印路径以及列出目录结构
        run: pwd | ls -R
